version: "3.9"
services:

  landingpage-prd:
    container_name: carboncase-landingpage-prd
    image: wordpress:6.1.1-php8.1-apache
    restart: unless-stopped
    volumes:
      - landingpage:/var/www/html
    labels:
      - traefik.http.routers.carboncase-landingpage-prd.rule=Host(`carboncase.energietransitiewindesheim.nl`)
      - traefik.http.routers.carboncase-landingpage-prd.tls=true
      - traefik.http.routers.carboncase-landingpage-prd.tls.certresolver=lets-encrypt
      - traefik.http.services.carboncase-landingpage-prd.loadbalancer.server.port=80
    environment:
      - WORDPRESS_DB_HOST=database-prd
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
    networks:
      - default
      - web
    depends_on:
      - database-prd
  
  database-prd:
    container_name: carboncase-database-prd
    image: mariadb:10.10.2-jammy
    restart: unless-stopped
    volumes:
      - database:/var/lib/mysql
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=wordpress
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
    networks:
      - default

  app-prd:
    container_name: carboncase-app-prd
    image: <your image name>:${APP_TAG}
    restart: unless-stopped
    labels:
      - traefik.http.routers.carboncase-app-prd.rule=Host(`app.carboncase.energietransitiewindesheim.nl`)
      - traefik.http.routers.carboncase-app-prd.tls=true
      - traefik.http.routers.carboncase-app-prd.tls.certresolver=lets-encrypt
      - traefik.http.services.carboncase-app-prd.loadbalancer.server.port=80
    # environment:
    #   - KEY=val
    networks:
      - web

  app-api-prd:
    container_name: carboncase-app-api-prd
    image: <your image name>:${APP_API_TAG}
    restart: unless-stopped
    labels:
      - traefik.http.routers.carboncase-app-api-prd.rule=Host(`api.app.carboncase.energietransitiewindesheim.nl`)
      - traefik.http.routers.carboncase-app-api-prd.tls=true
      - traefik.http.routers.carboncase-app-api-prd.tls.certresolver=lets-encrypt
      - traefik.http.services.carboncase-app-api-prd.loadbalancer.server.port=5000
    # environment:
    #   - KEY=val
    networks:
      - web

  management-prd:
    container_name: carboncase-management-prd
    image: <your image name>:${MANAGEMENT_TAG}
    restart: unless-stopped
    labels:
      - traefik.http.routers.carboncase-management-prd.rule=Host(`dash.carboncase.energietransitiewindesheim.nl`)
      - traefik.http.routers.carboncase-management-prd.tls=true
      - traefik.http.routers.carboncase-management-prd.tls.certresolver=lets-encrypt
      - traefik.http.services.carboncase-management-prd.loadbalancer.server.port=80
    # environment:
    #   - KEY=val
    networks:
      - web

  management-api-prd:
    container_name: carboncase-management-prd
    image: <your image name>:${MANAGEMENT_API_TAG}
    restart: unless-stopped
    labels:
      - traefik.http.routers.carboncase-management-api-prd.rule=Host(`api.dash.carboncase.energietransitiewindesheim.nl`)
      - traefik.http.routers.carboncase-management-api-prd.tls=true
      - traefik.http.routers.carboncase-management-api-prd.tls.certresolver=lets-encrypt
      - traefik.http.services.carboncase-management-api-prd.loadbalancer.server.port=5002
    # environment:
    #   - KEY=val
    networks:
      - web

volumes:
  landingpage: {}
  database: {}

networks:
  web:
    external: true